### ISSUE TITLE
NightmareWolf54

### ISSUE THREAD

**Issue by zai1208** [zai1208/zai1208.github.io#1]
Stop editing this repository and making it cause 100000000 issues

**Comment by zai1208** [comment]
Please stop @NightmareWolf54

**Comment by zai1208** [comment]
Please stop @NightmareWolf54

**Comment by zai1208** [comment]
Please stop @NightmareWolf54

**Comment by zai1208** [comment]
Please stop @NightmareWolf54

**Comment by zai1208** [comment]
Please stop @NightmareWolf54

**Comment by zai1208** [comment]
Please stop @NightmareWolf54

**Comment by zai1208** [comment]
Please stop @NightmareWolf54

**Comment by NightmareWolf54** [comment]
Spammmk

Crack the code : I-EH A-MEH ONEA-LEH       (´༎ຶོρ༎ຶོ`)

On 11 Sep 2020, at 11:20 am, zai1208 <notifications@github.com> wrote:

﻿

Please stop @NightmareWolf54<https://github.com/NightmareWolf54>

**Comment by zai1208** [comment]
Accidentally spammed and closed issue

**Comment by NightmareWolf54** [comment]
I’m he
Getting spammed

Crack the code : I-EH A-MEH ONEA-LEH       (´༎ຶོρ༎ຶོ`)

On 11 Sep 2020, at 11:20 am, zai1208 <notifications@github.com> wrote:

﻿

Please stop @NightmareWolf54<https://github.com/NightmareWolf54>

**Comment by zai1208** [comment]
You little !!!!!

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by zai1208** [comment]
#(#(#)You stop you little problem causer!””””!!”$*$*

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208

**Comment by NightmareWolf54** [comment]
Stop @zai1208 ur a meani

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by zai1208** [comment]
Removed @NightmareWolf54 
Yay 😀

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208

**Comment by NightmareWolf54** [comment]
Ur a meanie @zai1208
